### ISSUE TITLE
Dev/build server failing on execution

### ISSUE THREAD

**Issue by MickJasker** [mediamonks/pota#17]
When `npm run dev` or `npm run build` are run the following error is thrown:

```bash
file:///**/project/node_modules/@pota/webpack-skeleton/pota/webpack/getConfig.js:21
  if (path) return (await import(path)).default;
                    ^^^^^

SyntaxError: Unexpected reserved word

```

Inspecting the `getConfig` file you can see that the function that this piece of code is part of is not an `async` function triggering the error.

**Comment by psimk** [comment]
This was fixed in https://github.com/mediamonks/pota/commit/86e69420d3f069d1d271f7aca6d4012b8bb8198f (I missed the `async` mark before `function` :disappointed: )
