### ISSUE TITLE
remove `format` script

### ISSUE THREAD

**Issue by psimk** [mediamonks/pota#19]
All of the skeletons are using the [@mediamonks/eslint-config-base](https://github.com/mediamonks/eslint-config/tree/main/configs/base) eslint rule-set, which includes the [eslint-plugin-prettier](https://github.com/prettier/eslint-plugin-prettier) plugin. The [eslint-plugin-prettier](https://github.com/prettier/eslint-plugin-prettier) plugin already applies `prettier`'s formatting.

This means that the `format` script that runs `prettier` is redundant and can be removed.

**Comment by ThaNarie** [comment]
Doesn't prettier run on more files than eslint supports?

I don't want to have the same conversation twice, so maybe better to continue here https://github.com/mediamonks/eslint-config/pull/25#issuecomment-1013517641?

**Comment by psimk** [comment]
resolved in https://github.com/mediamonks/eslint-config/pull/25#issuecomment-1015209730
