### ISSUE TITLE
Enhance message for users running a project on a used port

### ISSUE THREAD

**Issue by pigeonfresh** [mediamonks/pota#21]
Running a dev server of a muban project installed through pota on a port that is already in use confronts the user with a wall of feedback. It feels this could be handled more gracefully or even better: a suggestion to run the project on a different port.

**Comment by psimk** [comment]
This seems to be an old issue, as I would not consider as a single line in the terminal mentioning that the development server is picking a different, unused port, as a "wall of feedback".

![image](https://user-images.githubusercontent.com/21334130/163988327-3cfe049b-1d87-4016-8c80-090d75339e55.png)
