### ISSUE TITLE
Error when running npx porter create on npm v7

### ISSUE THREAD

**Issue by psimk** [mediamonks/pota#8]
In npm 7, the 'npx' command has been changed to use 'npm exec' under the hood.

reference: https://github.blog/2021-02-02-npm-7-is-now-generally-available/

Tested on `node v15.10` with `npm v7.5.3`

When running `npx porter create react my-react-app`, npm errors with `could not determine executable to run`

**Comment by ThaNarie** [comment]
More specifically:

* https://github.blog/2020-10-13-presenting-v7-0-0-of-the-npm-cli/
* https://blog.npmjs.org/post/626173315965468672/npm-v7-series-beta-release-and-semver-major

But, what does it break in porter? A breaking change doesn't break anything in itself if you didn't make use of it, so it's always something else that breaks.
